openapi: 3.0.1

info:
  title: PERFECT.PERMUTATION.API.YML
  version: 1.0.0

paths:
  /version:
    get:
      tags:
        - PerfectPermutation
      operationId: version
      summary: returns the software version
      responses:
        '200':
          $ref: "#/components/responses/VersionResponse"

  /find/{numberOfElements}/{algorithm}:
    get:
      tags:
        - PerfectPermutation
      operationId: calculatePermutation
      summary: calculates the perfect permutation for that number of elements
      parameters:
        - in: path
          required: true
          name: numberOfElements
          schema:
            type: integer
        - in: path
          required: true
          name: algorithm
          schema:
            type: string
            enum:
              - SQUARE
              - SQUARE2
              - CIRCLE
              - ROW
              - SPACED
      responses:
        '200': # status code
          $ref: "#/components/responses/PerfectPermutationResponse"

  /find/{numberOfElements}:
    get:
      tags:
        - PerfectPermutation
      operationId: calculatePerfectPermutation
      summary: calculates the perfect permutation for that number of elements
      parameters:
        - in: path
          required: true
          name: numberOfElements
          schema:
            type: integer
      responses:
        '200': # status code
          $ref: "#/components/responses/PerfectPermutationResponse"


components:

  schemas:

    PerfectPermutationResponseContent:
      description: PerfectPermutationResponseContent
      properties:
        metainfo:
          $ref: "#/components/schemas/PerfectPermutationMetaInfo"
        square:
          $ref: "#/components/schemas/PerfectPermutationSquare"
        cycles:
          type: array
          items:
            $ref: "#/components/schemas/PerfectPermutationCycle"

    PerfectPermutationMetaInfo:
      description: PerfectPermutationMetaInfo
      properties:
        numberOfElements:
          type: integer
        status:
          type: string
        numberOfElementsWithMoreThanOneMatch:
          type: integer
        maxNumberOfMatchings:
          type: integer
        fillAlgorithm:
          type: string
        numberOfCycles:
          type: integer
        maxNumberOfGroups:
          type: integer
        minNumberOfGroups:
          type: integer
        maxElementsInLargestGroup:
          type: integer
        minElementsInSmallestGroup:
          type: integer

    PerfectPermutationCycle:
      description: PerfectPermutationMetaCycle
      type: array
      items:
        $ref: "#/components/schemas/PerfectPermutationGroup"

    PerfectPermutationGroup:
      description: PerfectPermutationMetaGroup
      type: array
      items:
        $ref: "#/components/schemas/PerfectPermutationElement"

    PerfectPermutationElement:
      description: PerfectPermutationMetaElement
      type: integer

    VersionResponseContent:
      description: VersionResponseContent
      properties:
        version:
          type: string

    PerfectPermutationSquare:
      description: PerfectPermutationSquare
      properties:
        array:
          type: array
          items:
            type: array
            items:
              type: integer
        dimension:
          type: integer
        numberOfElements:
          type: integer
        fillAlgorithm:
          type: string

  responses:
    PerfectPermutationResponse:
      description: PerfectPermutationResponse
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PerfectPermutationResponseContent"

    VersionResponse:
      description: VersionResponse
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/VersionResponseContent"

